### ISSUE TITLE
If you click on color text (causing the picker box to appear), and drag selection, the picker should probably disappear?

### ISSUE THREAD

**Issue by increpare** [enjalot/Inlet#25]

**Comment by georules** [comment]
I prefer to have it remain open until focus is lost.  Having it open allows you to click around the color space.  I don't usually have one color in mind that I want to drag to instantly.

**Comment by increpare** [comment]
Ah, no, sorry for the confusion - I mean dragging a text selection, not dragging a color selection:

<img width="996" alt="screen shot 2015-09-25 at 11 57 15" src="https://cloud.githubusercontent.com/assets/465632/10098895/a115369c-637c-11e5-97c0-543e7c0deed6.png">

**Comment by georules** [comment]
I see now, yeah this should probably be handled better.  I'll take a look at it.

**Comment by georules** [comment]
Check out this branch and tell me if you like the way this works.

1. Items react to mouseup instead of mousedown (so we see what happened from the click instead of at the start of the click
2. If the result of the click was a selection, we bail out of the onClick function that would then decide to bring up some kind of picker.

https://github.com/georules/Inlet/tree/test-drag

**Comment by increpare** [comment]
seems pretty good to me!

**Comment by enjalot** [comment]
I think this is better. want to make a PR and I'll merge it?
